export interface AlumniSection {
  title: string;
  content: string;
  images?: string[];
  quickLinks?: { text: string; slug: string; icon?: string }[];
}

export const staticAlumniSections: Record<string, AlumniSection> = {
  "home": {
    "title": "Alumni Association",
    "content": "__Alumni Home Page__\n\nWelcome to the Alumni Association of St. Ann’s College for Women, Gorantla, Guntur. The Alumni Association serves as a vibrant platform that connects former students with their alma mater and promotes lifelong relationships built on shared memories, values, and achievements.\n\nOur alumni are valuable ambassadors of the institution, contributing significantly in the fields of education, business, administration, research, social service, entrepreneurship, and public leadership. The association strives to strengthen alumni engagement through networking, mentorship, reunions, academic support, and institutional development activities.\n\n__Message from the Principal__\n\nDear Alumni, Greetings from St. Ann’s College for Women, Gorantla, Guntur. It gives us immense pleasure to welcome all our esteemed alumni to remain connected with the institution. Your journey, achievements, and experiences continue to inspire our students and strengthen the legacy of the college.\n\nThe Alumni Association plays an important role in building strong relationships between former students and the institution. Your support through mentoring, career guidance, academic interaction, and community engagement contributes greatly to the growth and development of our students.\n\nWe invite you to actively participate in alumni activities, reunions, institutional programmes, and collaborative initiatives. Your continued association with the college will help us move forward with excellence, innovation, and service.\n\n__Alumni Committee__\n\nThe Alumni Committee of St. Ann’s College for Women plays a vital role in strengthening the relationship between the institution and its alumni. The committee promotes alumni engagement, networking, mentorship, career guidance, and institutional development activities.\n\n__Alumni Committee Members__\n\n<table>\n<thead><tr><th>__Name__</th><th>__Designation / Department__</th><th>__Role__</th></tr></thead>\n<tbody>\n<tr><td>Dr. Sr. Sandhya Thumma</td><td>Principal, Department of MBA</td><td>Chairperson</td></tr>\n<tr><td>Mrs. R. Sharon Rose</td><td>Vice Principal, Department of Commerce</td><td>IQAC Coordinator</td></tr>\n<tr><td>Mrs. G. Saroja</td><td>Department of Commerce</td><td>Convener</td></tr>\n<tr><td>Mrs. D. V. Ramanamma</td><td>President, Alumni Association</td><td>Co-Convener</td></tr>\n</tbody>\n</table>\n\n__Upcoming Events__\n\n<table>\n<thead><tr><th>__Event__</th><th>__Tentative Date__</th></tr></thead>\n<tbody>\n<tr><td>Alumni Association Meeting</td><td>July</td></tr>\n<tr><td>Alumni Day Celebrations</td><td>August</td></tr>\n<tr><td>Career Guidance Session by Alumni</td><td>September</td></tr>\n<tr><td>Entrepreneurship Awareness Programme</td><td>October</td></tr>\n<tr><td>Batch-wise Reunion Meet</td><td>December</td></tr>\n</tbody>\n</table>\n\nLink: /documents/alumni/1.Alumni home.pdf",
    "quickLinks": [
      { "text": "Register as Alumni", "slug": "register", "icon": "UserPlus" },
      { "text": "Donate Now", "slug": "donate", "icon": "Heart" },
      { "text": "Upcoming Reunion", "slug": "re-union", "icon": "Users" },
      { "text": "Alumni Directory", "slug": "alumni-connect", "icon": "Book" },
      { "text": "Distinguished Alumni", "slug": "alumni-connect", "icon": "Award" },
      { "text": "Alumni Newsletter", "slug": "gallery", "icon": "Newspaper" }
    ]
  },
  "about-alumni-association": {
    "title": "About Alumni Association",
    "content": "__About the Association__\n\nThe Alumni Association of St. Ann’s College for Women, Gorantla, Guntur was established to strengthen the lifelong bond between the institution and its former students. The association serves as a platform for alumni interaction, networking, mentorship, institutional support, and community engagement.\n\n__Motto__\n\n“Educate • Enrich • Empower”\n\n__Vision__\n\nTo build a strong and vibrant alumni network that contributes to academic excellence, women empowerment, social responsibility, and institutional development while upholding the values and mission of St. Ann’s College for Women.\n\n__Mission__\n\n- To strengthen the relationship between alumni and the institution\n- To promote lifelong learning, leadership, and professional growth\n- To support student mentoring, career guidance, and skill development\n- To encourage alumni participation in institutional development activities\n- To promote social responsibility and community engagement\n- To empower women through education, collaboration, and service\n\n__Office Bearers__\n\n<table>\n<thead><tr><th>__S. No__</th><th>__Name__</th><th>__Designation__</th><th>__Occupation / Position__</th></tr></thead>\n<tbody>\n<tr><td>1</td><td>Mrs. Venkata Ramana Matte</td><td>President</td><td>Lecturer</td></tr>\n<tr><td>2</td><td>Mrs. Vani Gundabommu</td><td>Vice President</td><td>Accountant</td></tr>\n<tr><td>3</td><td>Mrs. Santha Kumari Gangula</td><td>Secretary</td><td>Lecturer</td></tr>\n<tr><td>4</td><td>Mrs. Mary Anusha Lingareddy</td><td>Joint Secretary</td><td>Lecturer</td></tr>\n<tr><td>5</td><td>Mrs. Naga Ramya Sindhu Pochiraju</td><td>Treasurer</td><td>Banker</td></tr>\n<tr><td>6</td><td>Mrs. Anusha Dev Thotakura</td><td>Executive Member</td><td>Faculty</td></tr>\n<tr><td>7</td><td>Sr. Jancy Edakkalathur</td><td>Vice President</td><td>Administrative Member</td></tr>\n</tbody>\n</table>\n\nLink: /documents/alumni/Alumni Association Registration Certficate 2022.pdf\n\nLink: /documents/alumni/Registration Renewal 2023-2024.pdf\n\nLink: /documents/alumni/Rgistration Renwal 2024-2025.pdf\n\nLink: /documents/alumni/2.About Alumni Association.pdf",
  },
  "alumni-connect": {
    "title": "Alumni Connect",
    "content": "__Alumni Directory__\n\nThe Alumni Directory serves as a valuable platform for maintaining alumni records and promoting professional interaction among former students. The directory helps alumni reconnect with classmates, strengthen institutional relationships, and build a strong professional and academic alumni network.\n\n__Distinguished Alumni__\n\n<table>\n<thead><tr><th>__Name__</th><th>__Profession / Achievement__</th></tr></thead>\n<tbody>\n<tr><td>Dr. Mary Christina</td><td>Academician & Research Scholar</td></tr>\n<tr><td>Mrs. P. Jhansi Lakshmi</td><td>Banking Professional</td></tr>\n<tr><td>Ms. A. Keerthana</td><td>IT Professional</td></tr>\n<tr><td>Mrs. K. Bhavani</td><td>Entrepreneur</td></tr>\n<tr><td>Ms. T. Divya</td><td>Social Activist & Leader</td></tr>\n</tbody>\n</table>\n\n__Support & Contributions__\n\nDistinguished alumni contribute to the institution through:\n- Student Mentoring Programmes\n- Career Guidance Sessions\n- Guest Lectures & Workshops\n- Placement Support Activities\n- Entrepreneurship Awareness Programmes\n- Scholarships & Institutional Support\n\nLink: /documents/alumni/3.Alumni Connect.pdf",
  },
  "alumni-day": {
    "title": "Alumni Day",
    "content": "__Alumni Day Celebrations__\n\nEvery year, St. Ann’s College for Women celebrates Alumni Day to welcome back former students and celebrate their success. It is a day of nostalgia, reconnecting with friends and teachers, and sharing life journeys.\n\n__Major Highlights of Alumni Day__\n- Reconnecting with classmates and faculty members\n- Sharing professional experiences and success stories\n- Institutional updates and future developmental plans\n- Cultural programmes and interactive sessions\n- Honoring distinguished alumni for their achievements\n- Networking opportunities for professional growth\n\nLink: /documents/alumni/3.Alumni Connect.pdf",
  },
  "alumni-events": {
    "title": "Alumni Events",
    "content": "__Recent and Upcoming Events__\n\nThe Alumni Association organizes various events throughout the year to promote interaction and professional development.\n\n__Types of Events Organized__\n- Guest Lectures and Webinars by Distinguished Alumni\n- Career Guidance and Mentorship Sessions\n- Professional Development Workshops\n- Social Outreach and Community Service Activities\n- Batch-wise Interaction Programmes\n- Alumni Meets and Networking Forums\n\n__Downloads__\n- Annual Reports 2022-2023\n- Registration Form & Membership Form\n- Alumni Newsletters & Event Brochures\n- Meeting Minutes & Institutional Updates\n\nLink: /documents/alumni/Alumni Annual Reports 2022-2023.pdf",
  },
  "re-union": {
    "title": "Re-Union",
    "content": "__Batch-wise Reunions__\n\nThe college encourages and facilitates batch-wise reunions to help alumni reconnect with their peers and the institution. These meets provide a platform for sharing memories, professional updates, and strengthening the bond with the alma mater.\n\n__Upcoming Reunions__\n- Batch 1997 – 2000 Silver Jubilee Meet: Tentative December 2024\n- Batch 2010 – 2013 Decennial Reunion: Tentative January 2025\n- Global Alumni Virtual Meet: Quarterly Interaction\n\n__Plan Your Reunion__\nAlumni batches wishing to organize a reunion meet at the college campus are invited to contact the Alumni Office for administrative support and coordination.",
  },
  "gallery": {
    "title": "Gallery",
    "content": "__Memories Captured__\n\nExplore the journey of St. Ann’s College for Women through the eyes of its alumni. Our gallery showcases moments from Alumni Day celebrations, batch-wise reunions, guest lectures, and social outreach activities.\n\n__Gallery Includes__\n- Alumni Day Celebrations Photographs\n- Batch-wise Reunion Memories\n- Distinguished Alumni Visit Highlights\n- Alumni Interaction & Mentoring Sessions\n- Community Service & Outreach Events\n\n(Digital Gallery is being updated regularly. Check back soon for the latest memories.)",
  },
  "register": {
    "title": "Alumni Registration",
    "content": "__Join the Alumni Association__\n\nWe invite all former students of St. Ann’s College for Women to register and become life members of the Alumni Association. Staying connected helps you stay updated on college developments, networking opportunities, and alumni events.\n\n__Membership Benefits__\n- Lifelong connection with the alma mater\n- Access to the Global Alumni Network\n- Invitations to Alumni Meets and Reunions\n- Opportunities for mentoring and career guidance\n- Participation in institutional development activities\n- Regular updates through Alumni Newsletters\n\n__How to Register?__\n1. Download the Alumni Registration Form / Membership Form below.\n2. Fill in the required details and attach necessary documents.\n3. Submit the form to the Alumni Office or email a scanned copy.\n\nLink: /documents/alumni/Alumni Association Registration Certficate 2022.pdf",
  },
  "donate": {
    "title": "Support & Contributions",
    "content": "__Contribute to Your Alma Mater__\n\nThe St. Ann’s College for Women Alumni Association encourages alumni to contribute towards the growth and development of the institution. Your support helps us provide better facilities, scholarships, and opportunities for present students.\n\n__Areas of Contribution__\n- __Student Scholarships__: Support economically disadvantaged and meritorious students.\n- __Institutional Development__: Contribute to infrastructure and academic facility enhancement.\n- __Skill Development__: Support workshops, guest lectures, and professional training programmes.\n- __Social Outreach__: Contribute to community service and social responsibility initiatives.\n- __Research & Innovation__: Support research projects and entrepreneurial activities.\n\n__Donation Details__\nFor information related to bank details and donation process, please contact the Alumni Office or the Treasurer of the Alumni Association.\n\nLink: /documents/alumni/Alumni PAN Card Letter.pdf\n\nLink: /documents/alumni/Alumni PAN.pdf",
  },
  "contact-us": {
    "title": "Contact Us",
    "content": "__Get in Touch with Alumni Association__\n\nWe value your connection and feedback. Reach out to the Alumni Office for any information related to registration, events, contributions, or institutional interaction.\n\n__Alumni Office Details__\n- __Address__: St. Ann’s College for Women, Gorantla, Guntur - 522034\n- __Office Timings__: 9:00 AM to 4:00 PM (Working Days)\n- __Contact Number__: +91 863 2231381\n- __Email__: alumni@stannscollege.com\n\n__Alumni Coordinators__\n- Dr. Sr. Sandhya Thumma (Principal)\n- Mrs. R. Sharon Rose (Vice Principal & IQAC Coordinator)\n- Mrs. G. Saroja (Convener, Alumni Committee)\n\n__Quick Links__\n- [Alumni Registration Form](/alumni/register)\n- [Submit Feedback / Query](/alumni/contact-us)\n- [Frequently Asked Questions (FAQs)](/alumni/contact-us)",
  }
};
